# Generated by Django 5.1.4 on 2025-01-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['nome'], 'verbose_name': 'Item', 'verbose_name_plural': 'Itens'},
        ),
        migrations.AlterField(
            model_name='item',
            name='nome',
            field=models.CharField(max_length=200),
        ),
    ]
