# Generated by Django 5.1.4 on 2025-01-13 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lista_compras', '0003_alter_item_options_alter_item_nome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['nome'], 'verbose_name': 'Item', 'verbose_name_plural': 'Itens'},
        ),
    ]
